name: Deploy
on:
    push:
        branches: [main]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4.5.1
              with:
                  branch: gh-pages
                  folder: dist
                  clean-exclude: CNAME
